"""
Atomic NGINX Upstream Switcher & Reloader
Manages the configuration in deployment/nginx/conf.d/upstream.conf
and triggers zero-downtime reloads on the NGINX ingress container.
"""
import os
import re
import sys
import subprocess
from pathlib import Path
from typing import Optional, Tuple

ROOT_DIR = Path(__file__).resolve().parent.parent.parent
UPSTREAM_CONF_PATH = ROOT_DIR / "deployment" / "nginx" / "conf.d" / "upstream.conf"


def get_active_color() -> Tuple[str, str]:
    """
    Reads the current upstream configuration and returns (active_color, server_host).
    Defaults to ('blue', 'api-blue') if unparseable.
    """
    if not UPSTREAM_CONF_PATH.exists():
        return "blue", "api-blue"

    content = UPSTREAM_CONF_PATH.read_text(encoding="utf-8")
    match = re.search(r'server\s+(api-(blue|green)):8000', content)
    if match:
        return match.group(2), match.group(1)
    return "blue", "api-blue"


def get_standby_color(active_color: str) -> str:
    """Returns the alternate standby color."""
    return "green" if active_color.lower() == "blue" else "blue"


def generate_upstream_content(target_color: str) -> str:
    """Generates the NGINX upstream block targeting the specified color."""
    return (
        f"# Dynamically generated by Blue-Green Deployment Controller\n"
        f"upstream api_backend {{\n"
        f"    server api-{target_color}:8000 max_fails=2 fail_timeout=5s;\n"
        f"}}\n"
    )


def switch_upstream_file(target_color: str) -> bool:
    """
    Atomically writes new upstream configuration pointing to target_color.
    """
    try:
        UPSTREAM_CONF_PATH.parent.mkdir(parents=True, exist_ok=True)
        content = generate_upstream_content(target_color)
        UPSTREAM_CONF_PATH.write_text(content, encoding="utf-8")
        return True
    except Exception as e:
        print(f"[!] Error updating upstream configuration: {e}")
        return False


def reload_nginx_ingress(container_name: str = "healthcare-nginx", simulate: bool = False) -> Tuple[bool, str]:
    """
    Instructs NGINX container to reload configuration without dropping connections:
    'docker exec <container> nginx -s reload'
    """
    if simulate:
        return True, "SIMULATED: NGINX ingress received SIGHUP / 'nginx -s reload'. Traffic seamlessly shifted."

    try:
        cmd = ["docker", "exec", container_name, "nginx", "-s", "reload"]
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
        if res.returncode == 0:
            return True, f"Successfully reloaded NGINX container '{container_name}'"
        else:
            return False, f"Failed to reload NGINX: {res.stderr.strip() or res.stdout.strip()}"
    except Exception as e:
        return False, f"Failed to invoke docker reload command: {str(e)}"


if __name__ == "__main__":
    if len(sys.argv) > 1:
        target = sys.argv[1].lower()
        if target not in ["blue", "green"]:
            print("Usage: switch_upstream.py [blue|green]")
            sys.exit(1)
        active, _ = get_active_color()
        print(f"[*] Current active color: {active}")
        print(f"[*] Switching upstream to: {target}")
        if switch_upstream_file(target):
            print("[+] Upstream file updated successfully.")
            sys.exit(0)
        else:
            sys.exit(1)
    else:
        active, host = get_active_color()
        standby = get_standby_color(active)
        print(f"Active upstream: {active} ({host}) | Standby target: {standby}")
